version: '3.8'
services:
    work:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/work
            - avrodata:/backup
        environment:
            - PORT:5000
volumes:
  avrodata: